sudo : required
services:
    - docker
before_install:
    - docker build -t sandipan814/docker-react -f Dockerfile.dev .
script:
  - docker run -e CI=true sandipan814/docker-react npm run test
deploy:
    provider: elasticbeanstalk
    region: "ap-south-1"
    app: "docker-react"
    environment: "DockerReact-env"
    bucket-name: "elasticbeanstalk-ap-south-1-840688919527"
    bucket_path: "docker-react"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key:
        secure: "$AWS_SECRET_KEY"
